window:
  position:
    x: 200
    y: 200

  dimensions:
    columns: 120
    lines: 30

  padding:
    x: 6
    y: 6

  startup_mode: Windowed

colors:
  primary:
    background: '0x002B36'
    foreground: '0xB3B1AD'

  normal:
    black: '0x01060E'
    red: '0xEA6C73'
    green: '0x91B362'
    yellow: '0xF9AF4F'
    blue: '0x53BDFA'
    magenta: '0xFAE994'
    cyan: '0x90E1C6'
    white: '0xC7C7C7'

  bright:
    black: '0x686868'
    red: '0xF07178'
    green: '0xC2D94C'
    yellow: '0xFFB454'
    blue: '0x59C2FF'
    magenta: '0xFFEE99'
    cyan: '0x95E6CB'
    white: '0xFFFFFF'

font:
  normal:
    family: Liberation Mono
    style: Regular

  bold:
    family: Liberation Mono
    style: Bold

  italic:
    family: Liberation Mono
    style: Italic

  bold_italic:
    family: Liberation Mono
    style: Bold Italic

  size: 11

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
