---
- name: Set swap file variable
  set_fact:
    swapfile: /swapfile

- name: "Check if swap file '{{ swapfile }}' already exists"
  stat:
    path: "{{ swapfile }}"
  register: swapfile_check

- name: Check available swap before applying changes
  command: grep SwapTotal /proc/meminfo
  register: pre_swap_check

- debug:
    msg: "Current available swap before applying changes is {{ pre_swap_check.stdout }}"

- name: "Resize existing swap at '{{ swapfile }}' to {{ swap_space_gig }}G"
  when: swapfile_check.stat.exists
  become: yes
  block:
    - debug:
        msg: "Will update the swapfile at {{ swapfile }}"

    - name: Turn off current swap
      command: swapoff -a

    - name: Reallocate swap space
      command: "dd if=/dev/zero of=/{{ swapfile }} bs=1G count={{swap_space_gig }}"

    - name: Apply permissions
      file:
        path: "{{ swapfile }}"
        mode: 0600

    - name: Prepare swap file
      command: "mkswap {{ swapfile }}"

    - name: Turn on swap
      command: swapon -a

    - name: Set swapiness
      sysctl:
        name: vm.swappiness
        value: "60"

    - name: Check available swap after applying changes
      command: grep SwapTotal /proc/meminfo
      register: post_swap_check

    - debug:
        msg: "Current available swap after applying changes is {{ post_swap_check.stdout }}"