LANG=en_GB.UTF-8
PROJECTS=$HOME/projects
ENV=$PROJECTS/env
ZSH=$PROJECTS/oh-my-zsh

ZSH_THEME="robbyrussell"
CASE_SENSITIVE="true"
EDITOR='vim'

plugins=(git sudo)

OHMYZSH_SRC=$ZSH/oh-my-zsh.sh
[ -f $OHMYZSH_SRC ] && source $OHMYZSH_SRC

Z_SRC=$PROJECTS/z/z.sh
[ -f $Z_SRC ] && source $Z_SRC

CHEATSHEET_SRC=$ENV/config/zsh/cheatsheet
[ -f $CHEATSHEET_SRC ] && source $CHEATSHEET_SRC

KUBECTL_SRC=$ENV/config/kubernetes/zsh/kubectl
[ -f $KUBECTL_SRC ] && source $KUBECTL_SRC

MANAGED_ALIASES_SRC=$ENV/config/zsh/aliases
[ -f $MANAGED_ALIASES_SRC ] && source $MANAGED_ALIASES_SRC

LOCAL_ALIASES_SRC=$HOME/.local-aliases
[ -f $LOCAL_ALIASES_SRC ] && source $LOCAL_ALIASES_SRC