LANG=en_GB.UTF-8
ZSH=$HOME/projects/oh-my-zsh
ZSH_THEME="robbyrussell"
CASE_SENSITIVE="true"
EDITOR='vim'

plugins=(git sudo)

source $ZSH/oh-my-zsh.sh
. ~/projects/z/z.sh

# Cheat Sheet
function cheat {
    curl cheat.sh/"$1"
}

# kubectl
alias k=kubectl
source <(kubectl completion zsh)
complete -F __start_kubectl k

# Aliases - terminal
alias zshconfig="edit ~/.zshrc"
alias tx="tmuxinator"
alias open="xdg-open"

# Aliases - development
alias mi="mvn install"
alias mci="mvn clean install"
alias mist="mvn install -DskipTests"
alias mcist="mvn clean install -DskipTests"
alias gw="./gradlew"