- name: Setup local development environment
  hosts: localhost
  roles:
    - { role: development, tags: [ 'development' ] }
    - { role: tools, tags: [ 'tools' ] }
    - { role: docker, tags: [ 'docker' ] }
    - { role: jdk, tags: [ 'jdk' ] }
    - { role: fonts, tags: [ 'fonts' ] }
    - { role: terminal, tags: [ 'terminal' ] }
    - { role: kubernetes, tags: [ 'kubernetes' ] }
    - { role: 1password, tags: [ '1password' ] }
    - { role: rofi, tags: [ 'rofi' ] }
    - { role: alacritty, tags: [ 'never', 'alacritty' ] }
    - { role: swap, tags: [ 'never', 'configure-swap' ] }
    - { role: git, tags: [ 'never', 'configure-git' ] }
  vars_files:
    - vars/vars.yml