---
- name: Install fonts
  block:
    - debug:
        msg: "Install fonts"

    - name: Install fonts (apt)
      become: yes
      apt:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ fonts }}"